# Generated by Django 5.2.8 on 2025-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.TextField(blank=True, verbose_name='Портфолио'),
        ),
    ]
